export const ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  ORG_USER: 'ORG_USER',
  USER: 'USER',
  PARTNER: 'PARTNER',
};

export const ROLE_ACCESS_ADMIN_PAGE = [
  ROLE.ADMIN,
  ROLE.SUPER_ADMIN,
  ROLE.ORG_ADMIN,
  ROLE.ORG_USER,
  ROLE.PARTNER,
];
